# Use postgres/example user/password credentials
version: '3.10'

services:

  mapdatabase:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: example
  mapadminer:
    image: adminer
    restart: always
    ports:
      - 8060:8080
networks:
  map-network: